# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ProtoClasses.trending_pb2 as trending__pb2


class TrendingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrendingVideos = channel.unary_unary(
                '/Trending/GetTrendingVideos',
                request_serializer=trending__pb2.TrendingRequest.SerializeToString,
                response_deserializer=trending__pb2.TrendingPageVideos.FromString,
                )
        self.GetMultipleTrendingVideos = channel.unary_unary(
                '/Trending/GetMultipleTrendingVideos',
                request_serializer=trending__pb2.MultipleTrendingRequest.SerializeToString,
                response_deserializer=trending__pb2.TrendingPageVideos.FromString,
                )


class TrendingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrendingVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMultipleTrendingVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrendingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrendingVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendingVideos,
                    request_deserializer=trending__pb2.TrendingRequest.FromString,
                    response_serializer=trending__pb2.TrendingPageVideos.SerializeToString,
            ),
            'GetMultipleTrendingVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultipleTrendingVideos,
                    request_deserializer=trending__pb2.MultipleTrendingRequest.FromString,
                    response_serializer=trending__pb2.TrendingPageVideos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Trending', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trending(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrendingVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Trending/GetTrendingVideos',
            trending__pb2.TrendingRequest.SerializeToString,
            trending__pb2.TrendingPageVideos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMultipleTrendingVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Trending/GetMultipleTrendingVideos',
            trending__pb2.MultipleTrendingRequest.SerializeToString,
            trending__pb2.TrendingPageVideos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
