# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"\x1f\n\x0cVideoRequest\x12\x0f\n\x07videoId\x18\x01 \x01(\t\"\xec\x01\n\tVideoData\x12\x0f\n\x07videoId\x18\x01 \x01(\t\x12\x1b\n\x08uploader\x18\x02 \x01(\x0b\x32\t.Uploader\x12\x0e\n\x06length\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x12\n\nuploadDate\x18\x05 \x01(\t\x12\x18\n\x10isFamilyFriendly\x18\x06 \x01(\x08\x12\x0e\n\x06iFrame\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\r\n\x05views\x18\t \x01(\x03\x12\r\n\x05likes\x18\n \x01(\t\x12\r\n\x05title\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x0c \x01(\t\":\n\x08Uploader\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x13\n\x0bsubscribers\x18\x03 \x01(\t22\n\x05Video\x12)\n\x0cGetVideoInfo\x12\r.VideoRequest\x1a\n.VideoDatab\x06proto3')



_VIDEOREQUEST = DESCRIPTOR.message_types_by_name['VideoRequest']
_VIDEODATA = DESCRIPTOR.message_types_by_name['VideoData']
_UPLOADER = DESCRIPTOR.message_types_by_name['Uploader']
VideoRequest = _reflection.GeneratedProtocolMessageType('VideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOREQUEST,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:VideoRequest)
  })
_sym_db.RegisterMessage(VideoRequest)

VideoData = _reflection.GeneratedProtocolMessageType('VideoData', (_message.Message,), {
  'DESCRIPTOR' : _VIDEODATA,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:VideoData)
  })
_sym_db.RegisterMessage(VideoData)

Uploader = _reflection.GeneratedProtocolMessageType('Uploader', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADER,
  '__module__' : 'video_pb2'
  # @@protoc_insertion_point(class_scope:Uploader)
  })
_sym_db.RegisterMessage(Uploader)

_VIDEO = DESCRIPTOR.services_by_name['Video']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOREQUEST._serialized_start=15
  _VIDEOREQUEST._serialized_end=46
  _VIDEODATA._serialized_start=49
  _VIDEODATA._serialized_end=285
  _UPLOADER._serialized_start=287
  _UPLOADER._serialized_end=345
  _VIDEO._serialized_start=347
  _VIDEO._serialized_end=397
# @@protoc_insertion_point(module_scope)
